create_clock -name clk -period 25.0 [get_ports clk]
set_propagated_clock [get_clocks clk]
set_clock_uncertainty -setup 0.5  [get_clocks clk]
set_clock_uncertainty -hold  0.25 [get_clocks clk]
set_input_delay  -clock clk -max 5.0 [all_inputs]
set_output_delay -clock clk -max 5.0 [all_outputs]
